// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blog/blog.proto

package blog

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogDto) Reset() {
	*x = BlogDto{}
	mi := &file_blog_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogDto) ProtoMessage() {}

func (x *BlogDto) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogDto.ProtoReflect.Descriptor instead.
func (*BlogDto) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{0}
}

func (x *BlogDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlogDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogDto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BlogDto) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *BlogDto) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=authorId,proto3" json:"authorId,omitempty"`
	ImagePaths    []string               `protobuf:"bytes,4,rep,name=imagePaths,proto3" json:"imagePaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateBlogRequest) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

type GetBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogRequest) Reset() {
	*x = GetBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogRequest) ProtoMessage() {}

func (x *GetBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogRequest.ProtoReflect.Descriptor instead.
func (*GetBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBlogsRequest) Reset() {
	*x = GetAllBlogsRequest{}
	mi := &file_blog_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlogsRequest) ProtoMessage() {}

func (x *GetAllBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBlogsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBlogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllBlogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BlogsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*BlogDto             `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogsListResponse) Reset() {
	*x = BlogsListResponse{}
	mi := &file_blog_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogsListResponse) ProtoMessage() {}

func (x *BlogsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogsListResponse.ProtoReflect.Descriptor instead.
func (*BlogsListResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{4}
}

func (x *BlogsListResponse) GetBlogs() []*BlogDto {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type UpdateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogRequest) Reset() {
	*x = UpdateBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogRequest) ProtoMessage() {}

func (x *UpdateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogRequest) Reset() {
	*x = DeleteBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogRequest) ProtoMessage() {}

func (x *DeleteBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogResponse) Reset() {
	*x = DeleteBlogResponse{}
	mi := &file_blog_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogResponse) ProtoMessage() {}

func (x *DeleteBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBlogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`         // binary file content
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // original filename (opciono)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_blog_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{8}
}

func (x *UploadImageRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // putanja ili URL do uploadovane slike
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_blog_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{9}
}

func (x *UploadImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Messages for Like
type ToggleLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeRequest) Reset() {
	*x = ToggleLikeRequest{}
	mi := &file_blog_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeRequest) ProtoMessage() {}

func (x *ToggleLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleLikeRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{10}
}

func (x *ToggleLikeRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *ToggleLikeRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type ToggleLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"` // true ako je sada lajkovan, false ako je unlikovan
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeResponse) Reset() {
	*x = ToggleLikeResponse{}
	mi := &file_blog_blog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeResponse) ProtoMessage() {}

func (x *ToggleLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeResponse.ProtoReflect.Descriptor instead.
func (*ToggleLikeResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{11}
}

func (x *ToggleLikeResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type CountLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountLikesRequest) Reset() {
	*x = CountLikesRequest{}
	mi := &file_blog_blog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLikesRequest) ProtoMessage() {}

func (x *CountLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLikesRequest.ProtoReflect.Descriptor instead.
func (*CountLikesRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{12}
}

func (x *CountLikesRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type CountLikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountLikesResponse) Reset() {
	*x = CountLikesResponse{}
	mi := &file_blog_blog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLikesResponse) ProtoMessage() {}

func (x *CountLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLikesResponse.ProtoReflect.Descriptor instead.
func (*CountLikesResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{13}
}

func (x *CountLikesResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type IsLikedByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedByUserRequest) Reset() {
	*x = IsLikedByUserRequest{}
	mi := &file_blog_blog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedByUserRequest) ProtoMessage() {}

func (x *IsLikedByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedByUserRequest.ProtoReflect.Descriptor instead.
func (*IsLikedByUserRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{14}
}

func (x *IsLikedByUserRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *IsLikedByUserRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type IsLikedByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLikedByUserResponse) Reset() {
	*x = IsLikedByUserResponse{}
	mi := &file_blog_blog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLikedByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLikedByUserResponse) ProtoMessage() {}

func (x *IsLikedByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLikedByUserResponse.ProtoReflect.Descriptor instead.
func (*IsLikedByUserResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{15}
}

func (x *IsLikedByUserResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

// Messages for Comments
type CommentDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId        string                 `protobuf:"bytes,2,opt,name=blogId,proto3" json:"blogId,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentDto) Reset() {
	*x = CommentDto{}
	mi := &file_blog_blog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentDto) ProtoMessage() {}

func (x *CommentDto) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentDto.ProtoReflect.Descriptor instead.
func (*CommentDto) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{16}
}

func (x *CommentDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentDto) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CommentDto) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CommentDto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentDto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentDto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_blog_blog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCommentRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CreateCommentRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_blog_blog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{18}
}

func (x *GetCommentsRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type CommentsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentDto          `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsListResponse) Reset() {
	*x = CommentsListResponse{}
	mi := &file_blog_blog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsListResponse) ProtoMessage() {}

func (x *CommentsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsListResponse.ProtoReflect.Descriptor instead.
func (*CommentsListResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{19}
}

func (x *CommentsListResponse) GetComments() []*CommentDto {
	if x != nil {
		return x.Comments
	}
	return nil
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_blog_blog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_blog_blog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_blog_blog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_blog_blog_proto protoreflect.FileDescriptor

const file_blog_blog_proto_rawDesc = "" +
	"\n" +
	"\x0fblog/blog.proto\x12\x05blogs\x1a\x1cgoogle/api/annotations.proto\"}\n" +
	"\aBlogDto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bauthorId\x18\x04 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\"\x7f\n" +
	"\x11CreateBlogRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bauthorId\x18\x03 \x01(\x03R\bauthorId\x12\x1e\n" +
	"\n" +
	"imagePaths\x18\x04 \x03(\tR\n" +
	"imagePaths\" \n" +
	"\x0eGetBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x12GetAllBlogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"9\n" +
	"\x11BlogsListResponse\x12$\n" +
	"\x05blogs\x18\x01 \x03(\v2\x0e.blogs.BlogDtoR\x05blogs\"S\n" +
	"\x11UpdateBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"#\n" +
	"\x11DeleteBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteBlogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"D\n" +
	"\x12UploadImageRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"'\n" +
	"\x13UploadImageResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"G\n" +
	"\x11ToggleLikeRequest\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\"*\n" +
	"\x12ToggleLikeResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"+\n" +
	"\x11CountLikesRequest\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\"2\n" +
	"\x12CountLikesResponse\x12\x1c\n" +
	"\tlikeCount\x18\x01 \x01(\x03R\tlikeCount\"J\n" +
	"\x14IsLikedByUserRequest\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\"-\n" +
	"\x15IsLikedByUserResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\"\xa6\x01\n" +
	"\n" +
	"CommentDto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06blogId\x18\x02 \x01(\tR\x06blogId\x12\x1a\n" +
	"\bauthorId\x18\x03 \x01(\x03R\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"d\n" +
	"\x14CreateCommentRequest\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\x03R\bauthorId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\",\n" +
	"\x12GetCommentsRequest\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\"E\n" +
	"\x14CommentsListResponse\x12-\n" +
	"\bcomments\x18\x01 \x03(\v2\x11.blogs.CommentDtoR\bcomments\"@\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"&\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf2\t\n" +
	"\vBlogService\x12M\n" +
	"\n" +
	"CreateBlog\x12\x18.blogs.CreateBlogRequest\x1a\x0e.blogs.BlogDto\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/blogs\x12b\n" +
	"\vUploadImage\x12\x19.blogs.UploadImageRequest\x1a\x1a.blogs.UploadImageResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/blogs/upload\x12I\n" +
	"\aGetBlog\x12\x15.blogs.GetBlogRequest\x1a\x0e.blogs.BlogDto\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/blogs/{id}\x12V\n" +
	"\vGetAllBlogs\x12\x19.blogs.GetAllBlogsRequest\x1a\x18.blogs.BlogsListResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/blogs\x12R\n" +
	"\n" +
	"UpdateBlog\x12\x18.blogs.UpdateBlogRequest\x1a\x0e.blogs.BlogDto\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/api/blogs/{id}\x12Z\n" +
	"\n" +
	"DeleteBlog\x12\x18.blogs.DeleteBlogRequest\x1a\x19.blogs.DeleteBlogResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/blogs/{id}\x12f\n" +
	"\n" +
	"ToggleLike\x12\x18.blogs.ToggleLikeRequest\x1a\x19.blogs.ToggleLikeResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/blogs/{blogId}/like\x12c\n" +
	"\n" +
	"CountLikes\x12\x18.blogs.CountLikesRequest\x1a\x19.blogs.CountLikesResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/blogs/{blogId}/like\x12q\n" +
	"\rIsLikedByUser\x12\x1b.blogs.IsLikedByUserRequest\x1a\x1c.blogs.IsLikedByUserResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/blogs/{blogId}/likedByMe\x12h\n" +
	"\rCreateComment\x12\x1b.blogs.CreateCommentRequest\x1a\x11.blogs.CommentDto\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/blogs/{blogId}/comments\x12k\n" +
	"\vGetComments\x12\x19.blogs.GetCommentsRequest\x1a\x1b.blogs.CommentsListResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/blogs/{blogId}/comments\x12^\n" +
	"\rUpdateComment\x12\x1b.blogs.UpdateCommentRequest\x1a\x11.blogs.CommentDto\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/comments/{id}\x12f\n" +
	"\rDeleteComment\x12\x1b.blogs.DeleteCommentRequest\x1a\x1c.blogs.DeleteCommentResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/comments/{id}B\x1dZ\x1bapi-gateway/proto/blog;blogb\x06proto3"

var (
	file_blog_blog_proto_rawDescOnce sync.Once
	file_blog_blog_proto_rawDescData []byte
)

func file_blog_blog_proto_rawDescGZIP() []byte {
	file_blog_blog_proto_rawDescOnce.Do(func() {
		file_blog_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_blog_proto_rawDesc), len(file_blog_blog_proto_rawDesc)))
	})
	return file_blog_blog_proto_rawDescData
}

var file_blog_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_blog_blog_proto_goTypes = []any{
	(*BlogDto)(nil),               // 0: blogs.BlogDto
	(*CreateBlogRequest)(nil),     // 1: blogs.CreateBlogRequest
	(*GetBlogRequest)(nil),        // 2: blogs.GetBlogRequest
	(*GetAllBlogsRequest)(nil),    // 3: blogs.GetAllBlogsRequest
	(*BlogsListResponse)(nil),     // 4: blogs.BlogsListResponse
	(*UpdateBlogRequest)(nil),     // 5: blogs.UpdateBlogRequest
	(*DeleteBlogRequest)(nil),     // 6: blogs.DeleteBlogRequest
	(*DeleteBlogResponse)(nil),    // 7: blogs.DeleteBlogResponse
	(*UploadImageRequest)(nil),    // 8: blogs.UploadImageRequest
	(*UploadImageResponse)(nil),   // 9: blogs.UploadImageResponse
	(*ToggleLikeRequest)(nil),     // 10: blogs.ToggleLikeRequest
	(*ToggleLikeResponse)(nil),    // 11: blogs.ToggleLikeResponse
	(*CountLikesRequest)(nil),     // 12: blogs.CountLikesRequest
	(*CountLikesResponse)(nil),    // 13: blogs.CountLikesResponse
	(*IsLikedByUserRequest)(nil),  // 14: blogs.IsLikedByUserRequest
	(*IsLikedByUserResponse)(nil), // 15: blogs.IsLikedByUserResponse
	(*CommentDto)(nil),            // 16: blogs.CommentDto
	(*CreateCommentRequest)(nil),  // 17: blogs.CreateCommentRequest
	(*GetCommentsRequest)(nil),    // 18: blogs.GetCommentsRequest
	(*CommentsListResponse)(nil),  // 19: blogs.CommentsListResponse
	(*UpdateCommentRequest)(nil),  // 20: blogs.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),  // 21: blogs.DeleteCommentRequest
	(*DeleteCommentResponse)(nil), // 22: blogs.DeleteCommentResponse
}
var file_blog_blog_proto_depIdxs = []int32{
	0,  // 0: blogs.BlogsListResponse.blogs:type_name -> blogs.BlogDto
	16, // 1: blogs.CommentsListResponse.comments:type_name -> blogs.CommentDto
	1,  // 2: blogs.BlogService.CreateBlog:input_type -> blogs.CreateBlogRequest
	8,  // 3: blogs.BlogService.UploadImage:input_type -> blogs.UploadImageRequest
	2,  // 4: blogs.BlogService.GetBlog:input_type -> blogs.GetBlogRequest
	3,  // 5: blogs.BlogService.GetAllBlogs:input_type -> blogs.GetAllBlogsRequest
	5,  // 6: blogs.BlogService.UpdateBlog:input_type -> blogs.UpdateBlogRequest
	6,  // 7: blogs.BlogService.DeleteBlog:input_type -> blogs.DeleteBlogRequest
	10, // 8: blogs.BlogService.ToggleLike:input_type -> blogs.ToggleLikeRequest
	12, // 9: blogs.BlogService.CountLikes:input_type -> blogs.CountLikesRequest
	14, // 10: blogs.BlogService.IsLikedByUser:input_type -> blogs.IsLikedByUserRequest
	17, // 11: blogs.BlogService.CreateComment:input_type -> blogs.CreateCommentRequest
	18, // 12: blogs.BlogService.GetComments:input_type -> blogs.GetCommentsRequest
	20, // 13: blogs.BlogService.UpdateComment:input_type -> blogs.UpdateCommentRequest
	21, // 14: blogs.BlogService.DeleteComment:input_type -> blogs.DeleteCommentRequest
	0,  // 15: blogs.BlogService.CreateBlog:output_type -> blogs.BlogDto
	9,  // 16: blogs.BlogService.UploadImage:output_type -> blogs.UploadImageResponse
	0,  // 17: blogs.BlogService.GetBlog:output_type -> blogs.BlogDto
	4,  // 18: blogs.BlogService.GetAllBlogs:output_type -> blogs.BlogsListResponse
	0,  // 19: blogs.BlogService.UpdateBlog:output_type -> blogs.BlogDto
	7,  // 20: blogs.BlogService.DeleteBlog:output_type -> blogs.DeleteBlogResponse
	11, // 21: blogs.BlogService.ToggleLike:output_type -> blogs.ToggleLikeResponse
	13, // 22: blogs.BlogService.CountLikes:output_type -> blogs.CountLikesResponse
	15, // 23: blogs.BlogService.IsLikedByUser:output_type -> blogs.IsLikedByUserResponse
	16, // 24: blogs.BlogService.CreateComment:output_type -> blogs.CommentDto
	19, // 25: blogs.BlogService.GetComments:output_type -> blogs.CommentsListResponse
	16, // 26: blogs.BlogService.UpdateComment:output_type -> blogs.CommentDto
	22, // 27: blogs.BlogService.DeleteComment:output_type -> blogs.DeleteCommentResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_blog_blog_proto_init() }
func file_blog_blog_proto_init() {
	if File_blog_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_blog_proto_rawDesc), len(file_blog_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_blog_proto_goTypes,
		DependencyIndexes: file_blog_blog_proto_depIdxs,
		MessageInfos:      file_blog_blog_proto_msgTypes,
	}.Build()
	File_blog_blog_proto = out.File
	file_blog_blog_proto_goTypes = nil
	file_blog_blog_proto_depIdxs = nil
}
