// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: blog/blog.proto

package blog

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogDto) Reset() {
	*x = BlogDto{}
	mi := &file_blog_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogDto) ProtoMessage() {}

func (x *BlogDto) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogDto.ProtoReflect.Descriptor instead.
func (*BlogDto) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{0}
}

func (x *BlogDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlogDto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogDto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BlogDto) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *BlogDto) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=authorId,proto3" json:"authorId,omitempty"`
	ImagePaths    []string               `protobuf:"bytes,4,rep,name=imagePaths,proto3" json:"imagePaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateBlogRequest) GetImagePaths() []string {
	if x != nil {
		return x.ImagePaths
	}
	return nil
}

type GetBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogRequest) Reset() {
	*x = GetBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogRequest) ProtoMessage() {}

func (x *GetBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogRequest.ProtoReflect.Descriptor instead.
func (*GetBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBlogsRequest) Reset() {
	*x = GetAllBlogsRequest{}
	mi := &file_blog_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlogsRequest) ProtoMessage() {}

func (x *GetAllBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBlogsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBlogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllBlogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BlogsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*BlogDto             `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogsListResponse) Reset() {
	*x = BlogsListResponse{}
	mi := &file_blog_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogsListResponse) ProtoMessage() {}

func (x *BlogsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogsListResponse.ProtoReflect.Descriptor instead.
func (*BlogsListResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{4}
}

func (x *BlogsListResponse) GetBlogs() []*BlogDto {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type UpdateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogRequest) Reset() {
	*x = UpdateBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogRequest) ProtoMessage() {}

func (x *UpdateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogRequest) Reset() {
	*x = DeleteBlogRequest{}
	mi := &file_blog_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogRequest) ProtoMessage() {}

func (x *DeleteBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogResponse) Reset() {
	*x = DeleteBlogResponse{}
	mi := &file_blog_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogResponse) ProtoMessage() {}

func (x *DeleteBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBlogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_blog_blog_proto protoreflect.FileDescriptor

const file_blog_blog_proto_rawDesc = "" +
	"\n" +
	"\x0fblog/blog.proto\x12\x05blogs\x1a\x1cgoogle/api/annotations.proto\"}\n" +
	"\aBlogDto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bauthorId\x18\x04 \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\"\x7f\n" +
	"\x11CreateBlogRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bauthorId\x18\x03 \x01(\x03R\bauthorId\x12\x1e\n" +
	"\n" +
	"imagePaths\x18\x04 \x03(\tR\n" +
	"imagePaths\" \n" +
	"\x0eGetBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x12GetAllBlogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"9\n" +
	"\x11BlogsListResponse\x12$\n" +
	"\x05blogs\x18\x01 \x03(\v2\x0e.blogs.BlogDtoR\x05blogs\"S\n" +
	"\x11UpdateBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"#\n" +
	"\x11DeleteBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteBlogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xaf\x03\n" +
	"\vBlogService\x12M\n" +
	"\n" +
	"CreateBlog\x12\x18.blogs.CreateBlogRequest\x1a\x0e.blogs.BlogDto\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/blogs\x12I\n" +
	"\aGetBlog\x12\x15.blogs.GetBlogRequest\x1a\x0e.blogs.BlogDto\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/blogs/{id}\x12V\n" +
	"\vGetAllBlogs\x12\x19.blogs.GetAllBlogsRequest\x1a\x18.blogs.BlogsListResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/blogs\x12R\n" +
	"\n" +
	"UpdateBlog\x12\x18.blogs.UpdateBlogRequest\x1a\x0e.blogs.BlogDto\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/api/blogs/{id}\x12Z\n" +
	"\n" +
	"DeleteBlog\x12\x18.blogs.DeleteBlogRequest\x1a\x19.blogs.DeleteBlogResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/blogs/{id}B\x1dZ\x1bapi-gateway/proto/blog;blogb\x06proto3"

var (
	file_blog_blog_proto_rawDescOnce sync.Once
	file_blog_blog_proto_rawDescData []byte
)

func file_blog_blog_proto_rawDescGZIP() []byte {
	file_blog_blog_proto_rawDescOnce.Do(func() {
		file_blog_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_blog_proto_rawDesc), len(file_blog_blog_proto_rawDesc)))
	})
	return file_blog_blog_proto_rawDescData
}

var file_blog_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_blog_blog_proto_goTypes = []any{
	(*BlogDto)(nil),            // 0: blogs.BlogDto
	(*CreateBlogRequest)(nil),  // 1: blogs.CreateBlogRequest
	(*GetBlogRequest)(nil),     // 2: blogs.GetBlogRequest
	(*GetAllBlogsRequest)(nil), // 3: blogs.GetAllBlogsRequest
	(*BlogsListResponse)(nil),  // 4: blogs.BlogsListResponse
	(*UpdateBlogRequest)(nil),  // 5: blogs.UpdateBlogRequest
	(*DeleteBlogRequest)(nil),  // 6: blogs.DeleteBlogRequest
	(*DeleteBlogResponse)(nil), // 7: blogs.DeleteBlogResponse
}
var file_blog_blog_proto_depIdxs = []int32{
	0, // 0: blogs.BlogsListResponse.blogs:type_name -> blogs.BlogDto
	1, // 1: blogs.BlogService.CreateBlog:input_type -> blogs.CreateBlogRequest
	2, // 2: blogs.BlogService.GetBlog:input_type -> blogs.GetBlogRequest
	3, // 3: blogs.BlogService.GetAllBlogs:input_type -> blogs.GetAllBlogsRequest
	5, // 4: blogs.BlogService.UpdateBlog:input_type -> blogs.UpdateBlogRequest
	6, // 5: blogs.BlogService.DeleteBlog:input_type -> blogs.DeleteBlogRequest
	0, // 6: blogs.BlogService.CreateBlog:output_type -> blogs.BlogDto
	0, // 7: blogs.BlogService.GetBlog:output_type -> blogs.BlogDto
	4, // 8: blogs.BlogService.GetAllBlogs:output_type -> blogs.BlogsListResponse
	0, // 9: blogs.BlogService.UpdateBlog:output_type -> blogs.BlogDto
	7, // 10: blogs.BlogService.DeleteBlog:output_type -> blogs.DeleteBlogResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blog_blog_proto_init() }
func file_blog_blog_proto_init() {
	if File_blog_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_blog_proto_rawDesc), len(file_blog_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_blog_proto_goTypes,
		DependencyIndexes: file_blog_blog_proto_depIdxs,
		MessageInfos:      file_blog_blog_proto_msgTypes,
	}.Build()
	File_blog_blog_proto = out.File
	file_blog_blog_proto_goTypes = nil
	file_blog_blog_proto_depIdxs = nil
}
