--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: stakeholders; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA stakeholders;


ALTER SCHEMA stakeholders OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: People; Type: TABLE; Schema: stakeholders; Owner: postgres
--

CREATE TABLE stakeholders."People" (
    "Id" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Email" text NOT NULL
);


ALTER TABLE stakeholders."People" OWNER TO postgres;

--
-- Name: People_Id_seq; Type: SEQUENCE; Schema: stakeholders; Owner: postgres
--

ALTER TABLE stakeholders."People" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stakeholders."People_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: stakeholders; Owner: postgres
--

CREATE TABLE stakeholders."Users" (
    "Id" bigint NOT NULL,
    "Username" text NOT NULL,
    "Password" text NOT NULL,
    "Role" integer NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE stakeholders."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: stakeholders; Owner: postgres
--

ALTER TABLE stakeholders."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME stakeholders."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250714095444_InitialCreate	9.0.7
\.


--
-- Data for Name: People; Type: TABLE DATA; Schema: stakeholders; Owner: postgres
--

COPY stakeholders."People" ("Id", "UserId", "Email") FROM stdin;
1	1	pera@example.com
2	2	joca@example.com
3	3	admin@example.com
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: stakeholders; Owner: postgres
--

COPY stakeholders."Users" ("Id", "Username", "Password", "Role", "IsActive") FROM stdin;
2	jovan	123456789	2	t
3	admin	123456789	0	t
1	pera	123456789	1	t
\.


--
-- Name: People_Id_seq; Type: SEQUENCE SET; Schema: stakeholders; Owner: postgres
--

SELECT pg_catalog.setval('stakeholders."People_Id_seq"', 3, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: stakeholders; Owner: postgres
--

SELECT pg_catalog.setval('stakeholders."Users_Id_seq"', 3, true);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: People PK_People; Type: CONSTRAINT; Schema: stakeholders; Owner: postgres
--

ALTER TABLE ONLY stakeholders."People"
    ADD CONSTRAINT "PK_People" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: stakeholders; Owner: postgres
--

ALTER TABLE ONLY stakeholders."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: IX_People_UserId; Type: INDEX; Schema: stakeholders; Owner: postgres
--

CREATE UNIQUE INDEX "IX_People_UserId" ON stakeholders."People" USING btree ("UserId");


--
-- Name: IX_Users_Username; Type: INDEX; Schema: stakeholders; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON stakeholders."Users" USING btree ("Username");


--
-- Name: People FK_People_Users_UserId; Type: FK CONSTRAINT; Schema: stakeholders; Owner: postgres
--

ALTER TABLE ONLY stakeholders."People"
    ADD CONSTRAINT "FK_People_Users_UserId" FOREIGN KEY ("UserId") REFERENCES stakeholders."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

