// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: tours/tours.proto

package tours

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourTags int32

const (
	TourTags_TAG_UNSPECIFIED     TourTags = 0
	TourTags_TAG_CYCLING         TourTags = 1
	TourTags_TAG_CULTURE         TourTags = 2
	TourTags_TAG_ADVENTURE       TourTags = 3
	TourTags_TAG_FAMILY_FRIENDLY TourTags = 4
	TourTags_TAG_NATURE          TourTags = 5
	TourTags_TAG_CITY_TOUR       TourTags = 6
	TourTags_TAG_HISTORICAL      TourTags = 7
	TourTags_TAG_RELAXATION      TourTags = 8
	TourTags_TAG_WILDLIFE        TourTags = 9
	TourTags_TAG_NIGHT_TOUR      TourTags = 10
	TourTags_TAG_BEACH           TourTags = 11
	TourTags_TAG_MOUNTAINS       TourTags = 12
	TourTags_TAG_PHOTOGRAPHY     TourTags = 13
	TourTags_TAG_GUIDED          TourTags = 14
	TourTags_TAG_SELF_GUIDED     TourTags = 15
)

// Enum value maps for TourTags.
var (
	TourTags_name = map[int32]string{
		0:  "TAG_UNSPECIFIED",
		1:  "TAG_CYCLING",
		2:  "TAG_CULTURE",
		3:  "TAG_ADVENTURE",
		4:  "TAG_FAMILY_FRIENDLY",
		5:  "TAG_NATURE",
		6:  "TAG_CITY_TOUR",
		7:  "TAG_HISTORICAL",
		8:  "TAG_RELAXATION",
		9:  "TAG_WILDLIFE",
		10: "TAG_NIGHT_TOUR",
		11: "TAG_BEACH",
		12: "TAG_MOUNTAINS",
		13: "TAG_PHOTOGRAPHY",
		14: "TAG_GUIDED",
		15: "TAG_SELF_GUIDED",
	}
	TourTags_value = map[string]int32{
		"TAG_UNSPECIFIED":     0,
		"TAG_CYCLING":         1,
		"TAG_CULTURE":         2,
		"TAG_ADVENTURE":       3,
		"TAG_FAMILY_FRIENDLY": 4,
		"TAG_NATURE":          5,
		"TAG_CITY_TOUR":       6,
		"TAG_HISTORICAL":      7,
		"TAG_RELAXATION":      8,
		"TAG_WILDLIFE":        9,
		"TAG_NIGHT_TOUR":      10,
		"TAG_BEACH":           11,
		"TAG_MOUNTAINS":       12,
		"TAG_PHOTOGRAPHY":     13,
		"TAG_GUIDED":          14,
		"TAG_SELF_GUIDED":     15,
	}
)

func (x TourTags) Enum() *TourTags {
	p := new(TourTags)
	*p = x
	return p
}

func (x TourTags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourTags) Descriptor() protoreflect.EnumDescriptor {
	return file_tours_tours_proto_enumTypes[0].Descriptor()
}

func (TourTags) Type() protoreflect.EnumType {
	return &file_tours_tours_proto_enumTypes[0]
}

func (x TourTags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourTags.Descriptor instead.
func (TourTags) EnumDescriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

type TourStatus int32

const (
	TourStatus_STATUS_UNSPECIFIED TourStatus = 0
	TourStatus_STATUS_DRAFT       TourStatus = 1
	TourStatus_STATUS_PUBLISHED   TourStatus = 2
	TourStatus_STATUS_ARCHIVED    TourStatus = 3
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_DRAFT",
		2: "STATUS_PUBLISHED",
		3: "STATUS_ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_DRAFT":       1,
		"STATUS_PUBLISHED":   2,
		"STATUS_ARCHIVED":    3,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tours_tours_proto_enumTypes[1].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_tours_tours_proto_enumTypes[1]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

type TourDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []TourTags             `protobuf:"varint,5,rep,packed,name=tags,proto3,enum=tours.TourTags" json:"tags,omitempty"`
	UserId        int64                  `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tours.TourStatus" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourDto) Reset() {
	*x = TourDto{}
	mi := &file_tours_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourDto) ProtoMessage() {}

func (x *TourDto) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourDto.ProtoReflect.Descriptor instead.
func (*TourDto) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{0}
}

func (x *TourDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourDto) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourDto) GetTags() []TourTags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TourDto) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_STATUS_UNSPECIFIED
}

func (x *TourDto) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUserIdRequest) Reset() {
	*x = GetByUserIdRequest{}
	mi := &file_tours_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUserIdRequest) ProtoMessage() {}

func (x *GetByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{1}
}

func (x *GetByUserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ToursListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourDto             `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToursListResponse) Reset() {
	*x = ToursListResponse{}
	mi := &file_tours_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToursListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToursListResponse) ProtoMessage() {}

func (x *ToursListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToursListResponse.ProtoReflect.Descriptor instead.
func (*ToursListResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *ToursListResponse) GetTours() []*TourDto {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetByTouristIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTouristIdRequest) Reset() {
	*x = GetByTouristIdRequest{}
	mi := &file_tours_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTouristIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTouristIdRequest) ProtoMessage() {}

func (x *GetByTouristIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTouristIdRequest.ProtoReflect.Descriptor instead.
func (*GetByTouristIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *GetByTouristIdRequest) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

type PositionDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     int64                  `protobuf:"varint,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionDto) Reset() {
	*x = PositionDto{}
	mi := &file_tours_tours_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionDto) ProtoMessage() {}

func (x *PositionDto) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionDto.ProtoReflect.Descriptor instead.
func (*PositionDto) Descriptor() ([]byte, []int) {
	return file_tours_tours_proto_rawDescGZIP(), []int{4}
}

func (x *PositionDto) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *PositionDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

var File_tours_tours_proto protoreflect.FileDescriptor

const file_tours_tours_proto_rawDesc = "" +
	"\n" +
	"\x11tours/tours.proto\x12\x05tours\x1a\x1cgoogle/api/annotations.proto\"\xed\x01\n" +
	"\aTourDto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12#\n" +
	"\x04tags\x18\x05 \x03(\x0e2\x0f.tours.TourTagsR\x04tags\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\x03R\x06userId\x12)\n" +
	"\x06status\x18\a \x01(\x0e2\x11.tours.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\",\n" +
	"\x12GetByUserIdRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"9\n" +
	"\x11ToursListResponse\x12$\n" +
	"\x05tours\x18\x01 \x03(\v2\x0e.tours.TourDtoR\x05tours\"5\n" +
	"\x15GetByTouristIdRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\x03R\ttouristId\"e\n" +
	"\vPositionDto\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\x03R\ttouristId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude*\xba\x02\n" +
	"\bTourTags\x12\x13\n" +
	"\x0fTAG_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTAG_CYCLING\x10\x01\x12\x0f\n" +
	"\vTAG_CULTURE\x10\x02\x12\x11\n" +
	"\rTAG_ADVENTURE\x10\x03\x12\x17\n" +
	"\x13TAG_FAMILY_FRIENDLY\x10\x04\x12\x0e\n" +
	"\n" +
	"TAG_NATURE\x10\x05\x12\x11\n" +
	"\rTAG_CITY_TOUR\x10\x06\x12\x12\n" +
	"\x0eTAG_HISTORICAL\x10\a\x12\x12\n" +
	"\x0eTAG_RELAXATION\x10\b\x12\x10\n" +
	"\fTAG_WILDLIFE\x10\t\x12\x12\n" +
	"\x0eTAG_NIGHT_TOUR\x10\n" +
	"\x12\r\n" +
	"\tTAG_BEACH\x10\v\x12\x11\n" +
	"\rTAG_MOUNTAINS\x10\f\x12\x13\n" +
	"\x0fTAG_PHOTOGRAPHY\x10\r\x12\x0e\n" +
	"\n" +
	"TAG_GUIDED\x10\x0e\x12\x13\n" +
	"\x0fTAG_SELF_GUIDED\x10\x0f*a\n" +
	"\n" +
	"TourStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATUS_DRAFT\x10\x01\x12\x14\n" +
	"\x10STATUS_PUBLISHED\x10\x02\x12\x13\n" +
	"\x0fSTATUS_ARCHIVED\x10\x032\xbc\x01\n" +
	"\fToursService\x12E\n" +
	"\x06Create\x12\x0e.tours.TourDto\x1a\x0e.tours.TourDto\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/author/tour\x12e\n" +
	"\vGetByUserId\x12\x19.tours.GetByUserIdRequest\x1a\x18.tours.ToursListResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/author/tour/{userId}B4Z\x1dapi-gateway/proto/tours;tours\xaa\x02\x12ToursService.Protob\x06proto3"

var (
	file_tours_tours_proto_rawDescOnce sync.Once
	file_tours_tours_proto_rawDescData []byte
)

func file_tours_tours_proto_rawDescGZIP() []byte {
	file_tours_tours_proto_rawDescOnce.Do(func() {
		file_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)))
	})
	return file_tours_tours_proto_rawDescData
}

var file_tours_tours_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tours_tours_proto_goTypes = []any{
	(TourTags)(0),                 // 0: tours.TourTags
	(TourStatus)(0),               // 1: tours.TourStatus
	(*TourDto)(nil),               // 2: tours.TourDto
	(*GetByUserIdRequest)(nil),    // 3: tours.GetByUserIdRequest
	(*ToursListResponse)(nil),     // 4: tours.ToursListResponse
	(*GetByTouristIdRequest)(nil), // 5: tours.GetByTouristIdRequest
	(*PositionDto)(nil),           // 6: tours.PositionDto
}
var file_tours_tours_proto_depIdxs = []int32{
	0, // 0: tours.TourDto.tags:type_name -> tours.TourTags
	1, // 1: tours.TourDto.status:type_name -> tours.TourStatus
	2, // 2: tours.ToursListResponse.tours:type_name -> tours.TourDto
	2, // 3: tours.ToursService.Create:input_type -> tours.TourDto
	3, // 4: tours.ToursService.GetByUserId:input_type -> tours.GetByUserIdRequest
	2, // 5: tours.ToursService.Create:output_type -> tours.TourDto
	4, // 6: tours.ToursService.GetByUserId:output_type -> tours.ToursListResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tours_tours_proto_init() }
func file_tours_tours_proto_init() {
	if File_tours_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tours_tours_proto_rawDesc), len(file_tours_tours_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tours_tours_proto_goTypes,
		DependencyIndexes: file_tours_tours_proto_depIdxs,
		EnumInfos:         file_tours_tours_proto_enumTypes,
		MessageInfos:      file_tours_tours_proto_msgTypes,
	}.Build()
	File_tours_tours_proto = out.File
	file_tours_tours_proto_goTypes = nil
	file_tours_tours_proto_depIdxs = nil
}
